In [1]:
# ==========================================
# FINAL EVALUATION & COMPARISON
# PROJECT INITIALIZATION
# ==========================================

import os
import json
import pandas as pd
import numpy as np

print("=" * 70)
print("FINAL EVALUATION & COMPARISON")
print("=" * 70)

# Current project directory
PROJECT_PATH = os.getcwd()

print("\nProject Path:")
print(PROJECT_PATH)

# Show available items
print("\nAvailable items:")

for item in os.listdir(PROJECT_PATH):
    print("-", item)

======================================================================
FINAL EVALUATION & COMPARISON
======================================================================

Project Path:
d:\NIDS

Available items:
- .git
- .gitignore
- 02Day8Exp2.ipynb
- customer data
- data
- data_2018
- Day01.ipynb
- Day02.ipynb
- Day03.ipynb
- Day04.ipynb
- Day05.ipynb
- Day06.ipynb
- Day07.ipynb
- Day08Exp2.ipynb
- Day09Exp3.ipynb
- Day10Exp4.ipynb
- Day111_Final_Evaluation.ipynb
- exp_2_result
- exp_3_result
- exp_4_result
- featured selected
- models
- scaled

In [2]:
# ==========================================
# FIND EXPERIMENT RESULT FOLDERS
# ==========================================

print("=" * 70)
print("SEARCHING FOR EXPERIMENT RESULTS")
print("=" * 70)

experiment_folders = []

for root, dirs, files in os.walk(PROJECT_PATH):

    for folder in dirs:

        folder_lower = folder.lower()

        if (
            "exp2" in folder_lower
            or "exp3" in folder_lower
            or "exp4" in folder_lower
            or "experiment_2" in folder_lower
            or "experiment_3" in folder_lower
            or "experiment_4" in folder_lower
        ):

            full_path = os.path.join(
                root,
                folder
            )

            if full_path not in experiment_folders:
                experiment_folders.append(full_path)


print("\nFound experiment folders:")

if experiment_folders:

    for folder in experiment_folders:
        print("-", folder)

else:

    print("No experiment result folders found automatically.")

======================================================================
SEARCHING FOR EXPERIMENT RESULTS
======================================================================

Found experiment folders:
No experiment result folders found automatically.

In [3]:
# ==========================================
# FIND SAVED RESULT FILES
# ==========================================

print("=" * 70)
print("SEARCHING FOR SAVED RESULT FILES")
print("=" * 70)

result_files = []

extensions = (
    ".json",
    ".csv",
    ".txt",
    ".pkl",
    ".joblib"
)

for root, dirs, files in os.walk(PROJECT_PATH):

    for file in files:

        if file.lower().endswith(extensions):

            full_path = os.path.join(
                root,
                file
            )

            result_files.append(full_path)


print("\nSaved result files:")

for file in result_files:

    print("-", file)

print(
    "\nTotal result files found:",
    len(result_files)
)

======================================================================
SEARCHING FOR SAVED RESULT FILES
======================================================================

Saved result files:
- d:\NIDS\exp_2_result\experiment2_hybrid_config.pkl
- d:\NIDS\exp_2_result\experiment2_isolation_forest.pkl
- d:\NIDS\exp_2_result\experiment2_isolation_scaler.pkl
- d:\NIDS\exp_2_result\experiment2_random_forest.pkl
- d:\NIDS\exp_2_result\experiment2_train_medians.pkl
- d:\NIDS\exp_2_result\experiment_2_results.csv
- d:\NIDS\exp_2_result\experiment_2_zero_day_recall.csv
- d:\NIDS\exp_3_result\experiment_2_vs_experiment_3.csv
- d:\NIDS\exp_3_result\experiment_3_2018_results.csv
- d:\NIDS\exp_3_result\experiment_3_performance_change.csv
- d:\NIDS\exp_4_result\experiment_4_final_result.json
- d:\NIDS\exp_4_result\llm_security_explanation.txt
- d:\NIDS\exp_4_result\llm_security_prompt.txt
- d:\NIDS\exp_4_result\shap_feature_importance.csv
- d:\NIDS\models\Supervised_rf_model.pkl
- d:\NIDS\models\unsupervised_iso_model.pkl
- d:\NIDS\scaled\fitted_scaler.pkl

Total result files found: 17

In [4]:
# ==========================================
# LOAD EXPERIMENT 4 FINAL RESULT
# ==========================================

exp4_files = [
    file
    for file in result_files
    if "experiment_4_final_result.json" in file.lower()
]

if len(exp4_files) == 0:

    print("Experiment 4 final result not found.")

else:

    EXP4_RESULT_FILE = exp4_files[0]

    print("Experiment 4 result found:")
    print(EXP4_RESULT_FILE)

    with open(
        EXP4_RESULT_FILE,
        "r",
        encoding="utf-8"
    ) as f:

        exp4_result = json.load(f)

    print("\nExperiment 4 contents:")

    print(
        json.dumps(
            exp4_result,
            indent=4,
            ensure_ascii=False
        )
    )

Experiment 4 result found:
d:\NIDS\exp_4_result\experiment_4_final_result.json

Experiment 4 contents:
{
    "experiment": "Experiment 4 - Explainability, RAG and LLM",
    "prediction": "Benign / No Attack Detected",
    "random_forest_probability": 0.455,
    "selected_sample_index": 28,
    "top_features": [
        {
            "Feature": "Fwd Header Length",
            "Feature_Value": 72.0,
            "SHAP_Value": -0.07797107030523388
        },
        {
            "Feature": "Bwd Header Length",
            "Feature_Value": 32.0,
            "SHAP_Value": -0.05001706365692025
        },
        {
            "Feature": "Packet Length Max",
            "Feature_Value": 0.0,
            "SHAP_Value": 0.04723992524762915
        },
        {
            "Feature": "Init Bwd Win Bytes",
            "Feature_Value": 8192.0,
            "SHAP_Value": -0.04538257012386409
        },
        {
            "Feature": "Fwd IAT Std",
            "Feature_Value": 160586.078125,
            "SHAP_Value": -0.03370132881575588
        },
        {
            "Feature": "Flow Bytes/s",
            "Feature_Value": 0.0,
            "SHAP_Value": 0.027416552052887073
        },
        {
            "Feature": "Flow IAT Std",
            "Feature_Value": 131450.859375,
            "SHAP_Value": -0.022756537388113385
        },
        {
            "Feature": "Fwd Seg Size Min",
            "Feature_Value": 20.0,
            "SHAP_Value": -0.0218724686567072
        },
        {
            "Feature": "Packet Length Mean",
            "Feature_Value": 0.0,
            "SHAP_Value": 0.021584334894803443
        },
        {
            "Feature": "Fwd IAT Min",
            "Feature_Value": 1474.0,
            "SHAP_Value": 0.02065886748374772
        }
    ],
    "retrieved_knowledge": [
        {
            "title": "Network Anomaly",
            "Similarity": 0.2798360364778877
        },
        {
            "title": "Denial of Service",
            "Similarity": 0.24511104928062538
        },
        {
            "title": "Botnet Traffic",
            "Similarity": 0.1660569648409976
        }
    ],
    "llm_explanation": "**Explanation of Model Prediction**\n\nThe model has predicted that the network activity is benign and no attack is detected. The probability of an attack being detected is 0.455, indicating a relatively low confidence level in the detection. The low probability value, combined with the model's confidence that the activity is benign, suggests that the model is leaning towards a non-malicious explanation for the observed behavior.\n\n**Most Important Network Features**\n\nThe most important network features, as indicated by the SHAP values, are the Forward Header Length (Fwd Header Length), Bwd Header Length, and Packet Length Max. These features have the most significant impact on the prediction outcome. The values of these features are also within normal ranges, which further supports the model's prediction of benign activity.\n\n**Interpretation of SHAP Values**\n\nThe SHAP (SHapley Additive exPlanations) values represent the contribution of each feature to the prediction outcome. In this case, the SHAP values indicate that the Forward Header Length has the most significant impact on the prediction, with a value of -0.077971. This suggests that the length of the forward header has a significant effect on the model's decision to classify the activity as benign. The SHAP values provide insight into how each feature contributes to the prediction outcome.\n\n**Relation to Retrieved Cybersecurity Knowledge**\n\nThe observed behavior in the network activity is related to the retrieved cybersecurity knowledge on Network Anomalies. While the activity appears to be benign, the SHAP values suggest that the Forward Header Length is a significant factor in the model's decision. This could indicate that the network activity is not entirely normal, but rather a deviation from normal traffic behavior that is not indicative of an attack.\n\n**Security Interpretation**\n\nThe observed behavior in the network activity suggests a potential network anomaly that warrants further investigation. While the model has predicted benign activity, the SHAP values indicate that the Forward Header Length has a significant impact on the prediction outcome. This suggests that the network activity may not be entirely normal and warrants closer examination to determine whether it is a legitimate network anomaly or an indicator of a more serious threat.\n\nIn conclusion, the model's prediction of benign activity is supported by the most important network features, but the SHAP values indicate that the Forward Header Length has a significant impact on the prediction outcome. Further investigation is necessary to determine the nature of the observed behavior and whether it poses a security risk to the network."
}

In [5]:
# ==========================================
# EXPERIMENT 4 SUMMARY
# ==========================================

if "exp4_result" in globals():

    print("=" * 70)
    print("EXPERIMENT 4 SUMMARY")
    print("=" * 70)

    print(
        "Prediction:",
        exp4_result.get("prediction")
    )

    print(
        "RF Attack Probability:",
        exp4_result.get(
            "random_forest_probability"
        )
    )

    print(
        "Selected Sample:",
        exp4_result.get(
            "selected_sample_index"
        )
    )

    print(
        "\nRetrieved Knowledge:"
    )

    for item in exp4_result.get(
        "retrieved_knowledge",
        []
    ):

        print(
            "-",
            item.get("title"),
            "| Similarity:",
            round(
                item.get("Similarity", 0),
                4
            )
        )

    print("\nLLM Explanation:")
    print(
        exp4_result.get(
            "llm_explanation",
            "Not available"
        )
    )

else:

    print(
        "Experiment 4 result is not loaded."
    )

======================================================================
EXPERIMENT 4 SUMMARY
======================================================================
Prediction: Benign / No Attack Detected
RF Attack Probability: 0.455
Selected Sample: 28

Retrieved Knowledge:
- Network Anomaly | Similarity: 0.2798
- Denial of Service | Similarity: 0.2451
- Botnet Traffic | Similarity: 0.1661

LLM Explanation:
**Explanation of Model Prediction**

The model has predicted that the network activity is benign and no attack is detected. The probability of an attack being detected is 0.455, indicating a relatively low confidence level in the detection. The low probability value, combined with the model's confidence that the activity is benign, suggests that the model is leaning towards a non-malicious explanation for the observed behavior.

**Most Important Network Features**

The most important network features, as indicated by the SHAP values, are the Forward Header Length (Fwd Header Length), Bwd Header Length, and Packet Length Max. These features have the most significant impact on the prediction outcome. The values of these features are also within normal ranges, which further supports the model's prediction of benign activity.

**Interpretation of SHAP Values**

The SHAP (SHapley Additive exPlanations) values represent the contribution of each feature to the prediction outcome. In this case, the SHAP values indicate that the Forward Header Length has the most significant impact on the prediction, with a value of -0.077971. This suggests that the length of the forward header has a significant effect on the model's decision to classify the activity as benign. The SHAP values provide insight into how each feature contributes to the prediction outcome.

**Relation to Retrieved Cybersecurity Knowledge**

The observed behavior in the network activity is related to the retrieved cybersecurity knowledge on Network Anomalies. While the activity appears to be benign, the SHAP values suggest that the Forward Header Length is a significant factor in the model's decision. This could indicate that the network activity is not entirely normal, but rather a deviation from normal traffic behavior that is not indicative of an attack.

**Security Interpretation**

The observed behavior in the network activity suggests a potential network anomaly that warrants further investigation. While the model has predicted benign activity, the SHAP values indicate that the Forward Header Length has a significant impact on the prediction outcome. This suggests that the network activity may not be entirely normal and warrants closer examination to determine whether it is a legitimate network anomaly or an indicator of a more serious threat.

In conclusion, the model's prediction of benign activity is supported by the most important network features, but the SHAP values indicate that the Forward Header Length has a significant impact on the prediction outcome. Further investigation is necessary to determine the nature of the observed behavior and whether it poses a security risk to the network.

In [6]:
# ==========================================
# FIND EXPERIMENT 2 RESULTS
# ==========================================

print("=" * 70)
print("SEARCHING FOR EXPERIMENT 2 RESULTS")
print("=" * 70)

exp2_files = []

for file in result_files:

    file_lower = file.lower()

    if (
        "exp2" in file_lower
        or "experiment_2" in file_lower
    ):

        exp2_files.append(file)


print("\nExperiment 2 related files:")

if exp2_files:

    for file in exp2_files:
        print("-", file)

else:

    print(
        "No Experiment 2 files found automatically."
    )

======================================================================
SEARCHING FOR EXPERIMENT 2 RESULTS
======================================================================

Experiment 2 related files:
- d:\NIDS\exp_2_result\experiment_2_results.csv
- d:\NIDS\exp_2_result\experiment_2_zero_day_recall.csv
- d:\NIDS\exp_3_result\experiment_2_vs_experiment_3.csv

In [7]:
# ==========================================
# INSPECT EXPERIMENT 2 FILES
# ==========================================

print("=" * 70)
print("EXPERIMENT 2 FILE INSPECTION")
print("=" * 70)

for file in exp2_files:

    print("\n" + "-" * 70)
    print("FILE:", file)

    try:

        if file.lower().endswith(".json"):

            with open(
                file,
                "r",
                encoding="utf-8"
            ) as f:

                data = json.load(f)

            print(
                json.dumps(
                    data,
                    indent=2,
                    ensure_ascii=False
                )[:5000]
            )

        elif file.lower().endswith(".csv"):

            df_temp = pd.read_csv(file)

            print(
                "Shape:",
                df_temp.shape
            )

            display(
                df_temp.head()
            )

        elif file.lower().endswith(".txt"):

            with open(
                file,
                "r",
                encoding="utf-8",
                errors="ignore"
            ) as f:

                text = f.read()

            print(text[:5000])

    except Exception as e:

        print(
            "Could not inspect:",
            type(e).__name__,
            e
        )

======================================================================
EXPERIMENT 2 FILE INSPECTION
======================================================================

----------------------------------------------------------------------
FILE: d:\NIDS\exp_2_result\experiment_2_results.csv
Shape: (3, 7)

              Model  Precision    Recall        F1  PR-AUC  FPR       FNR
0     Random Forest        1.0  0.190476  0.320000     1.0  0.0  0.809524
1  Isolation Forest        0.0  0.000000  0.000000     1.0  0.0  1.000000
2            Hybrid        1.0  0.047619  0.090909     1.0  0.0  0.952381

----------------------------------------------------------------------
FILE: d:\NIDS\exp_2_result\experiment_2_zero_day_recall.csv
Shape: (3, 2)

              Model  Zero-Day Recall
0     Random Forest         0.190476
1  Isolation Forest         0.000000
2            Hybrid         0.047619

----------------------------------------------------------------------
FILE: d:\NIDS\exp_3_result\experiment_2_vs_experiment_3.csv
Shape: (6, 8)

,Model,Precision,Recall,F1,PR-AUC,FPR,FNR,Experiment
0,Random Forest,1.000000,0.190476,0.320000,1.000000,0.0,0.809524,Experiment 2
1,Isolation Forest,0.000000,0.000000,0.000000,1.000000,0.0,1.000000,Experiment 2
2,Hybrid,1.000000,0.047619,0.090909,1.000000,0.0,0.952381,Experiment 2
3,Random Forest,0.330882,0.000068,0.000135,0.191616,NaN,NaN,Experiment 3
4,Isolation Forest,0.056210,0.015814,0.024684,0.182102,NaN,NaN,Experiment 3

In [8]:
# ==========================================
# FINAL MODEL COMPARISON
# ==========================================

print("=" * 70)
print("FINAL MODEL COMPARISON")
print("=" * 70)

comparison_data = [
    {
        "Model": "Random Forest",
        "Precision": 1.0,
        "Recall": 0.190476,
        "F1": 0.320000,
        "PR-AUC": 1.0,
        "FPR": 0.0,
        "FNR": 0.809524
    },
    {
        "Model": "Isolation Forest",
        "Precision": 0.0,
        "Recall": 0.000000,
        "F1": 0.000000,
        "PR-AUC": 1.0,
        "FPR": 0.0,
        "FNR": 1.000000
    },
    {
        "Model": "Hybrid",
        "Precision": 1.0,
        "Recall": 0.047619,
        "F1": 0.090909,
        "PR-AUC": 1.0,
        "FPR": 0.0,
        "FNR": 0.952381
    }
]

final_comparison = pd.DataFrame(
    comparison_data
)

display(final_comparison)

======================================================================
FINAL MODEL COMPARISON
======================================================================

              Model  Precision    Recall        F1  PR-AUC  FPR       FNR
0     Random Forest        1.0  0.190476  0.320000     1.0  0.0  0.809524
1  Isolation Forest        0.0  0.000000  0.000000     1.0  0.0  1.000000
2            Hybrid        1.0  0.047619  0.090909     1.0  0.0  0.952381

In [9]:
# ==========================================
# BEST MODEL ANALYSIS
# ==========================================

best_f1_row = final_comparison.loc[
    final_comparison["F1"].idxmax()
]

best_recall_row = final_comparison.loc[
    final_comparison["Recall"].idxmax()
]

best_precision_row = final_comparison.loc[
    final_comparison["Precision"].idxmax()
]

print("=" * 70)
print("BEST MODEL ANALYSIS")
print("=" * 70)

print(
    "\nBest F1 Score:",
    best_f1_row["Model"],
    "->",
    best_f1_row["F1"]
)

print(
    "Best Recall:",
    best_recall_row["Model"],
    "->",
    best_recall_row["Recall"]
)

print(
    "Best Precision:",
    best_precision_row["Model"],
    "->",
    best_precision_row["Precision"]
)

======================================================================
BEST MODEL ANALYSIS
======================================================================

Best F1 Score: Random Forest -> 0.32
Best Recall: Random Forest -> 0.190476
Best Precision: Random Forest -> 1.0

In [10]:
# ==========================================
# SAVE FINAL COMPARISON
# ==========================================

FINAL_RESULTS_PATH = os.path.join(
    PROJECT_PATH,
    "Final_Project_Results"
)

os.makedirs(
    FINAL_RESULTS_PATH,
    exist_ok=True
)

comparison_csv = os.path.join(
    FINAL_RESULTS_PATH,
    "final_model_comparison.csv"
)

final_comparison.to_csv(
    comparison_csv,
    index=False
)

print("=" * 70)
print("FINAL COMPARISON SAVED")
print("=" * 70)

print(comparison_csv)

======================================================================
FINAL COMPARISON SAVED
======================================================================
d:\NIDS\Final_Project_Results\final_model_comparison.csv

In [11]:
# ==========================================
# FINAL PROJECT SUMMARY
# ==========================================

summary = {
    "Experiment_2": "Completed",
    "Experiment_3_SHAP": "Completed",
    "Experiment_4_RAG_LLM": "Completed",
    "Best_F1_Model": best_f1_row["Model"],
    "Best_F1": float(best_f1_row["F1"]),
    "Best_Recall_Model": best_recall_row["Model"],
    "Best_Recall": float(best_recall_row["Recall"])
}

summary_path = os.path.join(
    FINAL_RESULTS_PATH,
    "final_project_summary.json"
)

with open(
    summary_path,
    "w",
    encoding="utf-8"
) as f:

    json.dump(
        summary,
        f,
        indent=4
    )

print("=" * 70)
print("FINAL PROJECT SUMMARY")
print("=" * 70)

print(
    json.dumps(
        summary,
        indent=4
    )
)

print(
    "\nSummary saved:",
    summary_path
)

======================================================================
FINAL PROJECT SUMMARY
======================================================================
{
    "Experiment_2": "Completed",
    "Experiment_3_SHAP": "Completed",
    "Experiment_4_RAG_LLM": "Completed",
    "Best_F1_Model": "Random Forest",
    "Best_F1": 0.32,
    "Best_Recall_Model": "Random Forest",
    "Best_Recall": 0.190476
}

Summary saved: d:\NIDS\Final_Project_Results\final_project_summary.json